#=========================================
#========    Spring Boot Configuration
#==============-==========================
pom.version: '@version@'
build.date: '@maven.build.timestamp@'

# handle write dates
spring:
  profiles:
    active: '@activeProfile@'
  jackson:
    .serialization.write-dates-as-timestamps: false
    .time-zone: Asia/Singapore

